# Generated by Django 5.1.3 on 2025-06-19 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiogestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='imagen_referencia',
            field=models.ImageField(blank=True, help_text='Sube una imagen o captura como comprobante de pago', null=True, upload_to='pagos/referencias/'),
        ),
    ]
