# Generated by Django 5.1.3 on 2025-06-15 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisiogestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisioterapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('rol', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=100)),
                ('info_adicional', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='fisiogestion.paciente')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='fisiogestion.fisioterapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='fisiogestion.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Mensaje', 'Mensaje'), ('Archivo', 'Archivo'), ('Video', 'Video')], max_length=8)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='fisiogestion.paciente')),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunicaciones', to='fisiogestion.fisioterapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='fisiogestion.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('fisioterapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='fisiogestion.fisioterapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes, e.g. 2024-05-01')),
                ('total_pacientes', models.IntegerField()),
                ('total_sesiones', models.IntegerField()),
                ('ingresos_totales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('detalle_estadisticas', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('mes',)},
            },
        ),
        migrations.CreateModel(
            name='DocumentoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('Grafico', 'Gráfico')], max_length=7)),
                ('archivo', models.FileField(upload_to='informes/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('informe_mensual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='fisiogestion.informemensual')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_tratamiento', models.TextField()),
                ('fecha_informe', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_tratamiento', to='fisiogestion.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='fisiogestion.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='fisiogestion.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Teleconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(max_length=50)),
                ('enlace_sesion', models.URLField(max_length=255)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas', to='fisiogestion.consulta')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_ejercicios', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('documentos_adjuntos', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('instrucciones', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('teleconsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='fisiogestion.teleconsulta')),
            ],
        ),
    ]
